language: elixir
elixir:
  - 1.4.5
otp_release:
  - 20.0
sudo: false
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
after_success:
  - mix coveralls.travis
env:
  - MIX_ENV=test
